export const TagList = [
  'Astro',
  'CSS',
  'Docusaurus',
  'Front-end Engineering',
  'Gatsby',
  'Git',
  'HTML',
  'JavaScript',
  'Naive UI',
  'Next.js',
  'Node.js',
  'Nuxt.js',
  'PC',
  'PostgreSQL',
  'Prisma',
  'React',
  'SCSS',
  'SVG',
  'TailwindCSS',
  'TypeScript',
  'Vite',
  'Vue',
  'Web Tech'
] as const

export const TagHrefMap = new Map([
  ['Astro', 'astro'],
  ['CSS', 'css'],
  ['Docusaurus', 'docusaurus'],
  ['Front-end Engineering', 'front-end-engineering'],
  ['Gatsby', 'gatsby'],
  ['Git', 'git'],
  ['HTML', 'html'],
  ['JavaScript', 'javascript'],
  ['Naive UI', 'naive-ui'],
  ['Next.js', 'next-js'],
  ['Node.js', 'node-js'],
  ['Nuxt.js', 'nuxt-js'],
  ['PC', 'pc'],
  ['PostgreSQL', 'postgresql'],
  ['Prisma', 'prisma'],
  ['React', 'react'],
  ['SCSS', 'scss'],
  ['SVG', 'svg'],
  ['TailwindCSS', 'tailwind-css'],
  ['TypeScript', 'typescript'],
  ['Vite', 'vite'],
  ['Vue', 'vue'],
  ['Web Tech', 'web-tech']
])
